### ISSUE TITLE
undefined control sequence after proof environment

### ISSUE THREAD

**Issue by mlaves** [melba-journal/submission#1]
I'm using `This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020)`.

Using the proof environment, I get the following error:

```
! Undefined control sequence.
\@LN@do@vadjusts ...o@vadjusts \relax \reserved@f 
                                                  \vskip 2mm
l.115
```

I narrowed down the culprit to the `\\[2mm]` spacing in the `proof` definition in `melba.sty` l. 326.

**Comment by adalca** [comment]
@mlaves , thanks for this info. Just checking, but #2 solved this, right?

**Comment by mlaves** [comment]
Yes, issue fixed!
