### ISSUE TITLE
Typo in camera-ready instructions

### ISSUE THREAD

**Issue by abhineet123** [melba-journal/submission#7]
Smething seems to have been accidentally deleted in the middle of the last point in camera ready instructions:

"(Optional) authors can also send a **vid1e that route** for submission to MELBA), please update that version instead of creating a new arXiv submission."

**Comment by HKervadec** [comment]
Good catch, thanks! Seems I borged it in 8dadaf5 a while ago.

Fixed in 6b7e871.
