### ISSUE TITLE
Formatting issue

### ISSUE THREAD

**Issue by ReubenDo** [melba-journal/submission#9]
Hello Melba team,

I have some issues with the formatting of the v2 template with two columns. Some words appear in the other columns instead of going to the next line.
For example "Among" in this paper:
<img width="369" alt="image" src="https://github.com/melba-journal/submission/assets/17268715/c0c93314-b84e-4db9-acfc-e848d3d20239">

To reproduce:

\begin{itemize}
    \item \textit{CT Lymph Node dataset}: The NIH CT Lymph Node dataset~\citep{roth2014new} comprises a total of 176 contrast-enhanced CT series from 176 patients. Among them,
\end{itemize}

**Comment by HKervadec** [comment]
I cannot compile it right away, but from a distance, it looks like a box overflow (the alternative here for the LaTeX engine being having an even bigger underflow), that ends up in the margin between the two columns. Would replacing `among` with `am-ong` produce the desired split?

Overall, itemize for longer paragraphs might cause those issues to happen more often, as it "eats" 2/3 em of the column width. For your text, would using a `\paragraph{CT Lymph Node dataset}` or even `\noindent\emph{CT Lymph Node dataset}` make more sense?

**Comment by HKervadec** [comment]
I don't have the .bib so I retyped by hand, but here is the illustration of my previous response:
![latex](https://github.com/melba-journal/submission/assets/4191866/e0381427-6e0f-4809-b873-ca7380a37dc8)


```latex
\begin{itemize}
        \item \textit{CT Lymph Node dataset}: The NIH CT Lymph Node dataset~(Roth et al., 2014) comprises a total of 176 contrast-enhanced CT series from 176 patients. Among them,
        \item \textit{CT Lymph Node dataset}: The NIH CT Lymph Node dataset~(Roth et al., 2014) comprises a total of 176 contrast-enhanced CT series from 176 patients. Am-ong them,
\end{itemize}

\paragraph{CT Lymph Node dataset:} The NIH CT Lymph Node dataset~(Roth et al., 2014) comprises a total of 176 contrast-enhanced CT series from 176 patients. Among them,
```

**Comment by HKervadec** [comment]
The root cause of the issue is that the default `leftmargin` of `itemize` (and others) is too wide with two columns; so I changed the default value in 0377e1a8025b57bee92137e4461fc66e2a86b32e. Hopefully this will reduce how often those hyphenation issues arise.

**Comment by ReubenDo** [comment]
Brilliant! Thank you Hoel!
